apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-stream-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: music-stream-service
  template:
    metadata:
      labels:
        app: music-stream-service
    spec:
      containers:
      - name: music-stream-service
        image: alperio/music-stream-service:v1
        ports:
        - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: music-stream-service
spec:
  selector:
    app: music-stream-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 5002
  type: LoadBalancer
